version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  node:
    image: node:14
    container_name: node_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    command: bash -c "npm install && npm start"

volumes:
  db_data:

networks:
  app-network:
    driver: bridg